-- PostgreSQL schema for "backend_sejuta_berita"
-- Derived from the provided UML: User, News, Category, Comment (+ Tags)
-- Safe to re-run: drops existing objects in correct dependency order.

BEGIN;

-- 1) Drop in dependency order
DROP TABLE IF EXISTS news_tags CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS news CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS password_resets CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 2) Enums (CREATE IF NOT EXISTS for idempotency)
DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
		CREATE TYPE user_role AS ENUM ('admin','editor','user');
	END IF;
END$$;

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'news_status') THEN
		CREATE TYPE news_status AS ENUM ('draft','published','archived');
	END IF;
END$$;

-- 3) Core tables
CREATE TABLE users (
	id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name            VARCHAR(100),
	username        VARCHAR(50)  NOT NULL UNIQUE,
	email           VARCHAR(255) NOT NULL UNIQUE,
	password_hash   VARCHAR(255) NOT NULL,
	bio             TEXT,
	avatar          VARCHAR(255),
	role            user_role     NOT NULL DEFAULT 'user',
	registered_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
	is_active       BOOLEAN       NOT NULL DEFAULT TRUE,
	is_logged_in    BOOLEAN       NOT NULL DEFAULT FALSE
);

-- Token table for password reset
CREATE TABLE password_resets (
	id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	token        VARCHAR(128) NOT NULL UNIQUE,
	expires_at   TIMESTAMPTZ NOT NULL,
	used_at      TIMESTAMPTZ,
	created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE categories (
	id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name            VARCHAR(100) NOT NULL UNIQUE,
	description     TEXT
);

CREATE TABLE news (
	id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	category_id     BIGINT REFERENCES categories(id) ON DELETE SET NULL,
	author_id       BIGINT REFERENCES users(id)      ON DELETE SET NULL,
	title           VARCHAR(200) NOT NULL,
	content         TEXT         NOT NULL,
	-- Store image as a relative public path like '/uploads/berita-1.jpg'
	image           VARCHAR(512),
	status          news_status  NOT NULL DEFAULT 'draft',
	created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
	published_at    TIMESTAMPTZ
);

CREATE TABLE comments (
	id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	news_id         BIGINT NOT NULL REFERENCES news(id)   ON DELETE CASCADE,
	user_id         BIGINT REFERENCES users(id)           ON DELETE SET NULL,
	content         TEXT   NOT NULL,
	created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	is_approved     BOOLEAN NOT NULL DEFAULT FALSE
);

-- Optional: tag system for News.tags (List<Tag>) from UML
CREATE TABLE tags (
	id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name            VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE news_tags (
	news_id         BIGINT NOT NULL REFERENCES news(id) ON DELETE CASCADE,
	tag_id          BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
	PRIMARY KEY (news_id, tag_id)
);

-- 4) Helpful indexes
CREATE INDEX IF NOT EXISTS idx_news_category   ON news(category_id);
CREATE INDEX IF NOT EXISTS idx_news_author     ON news(author_id);
CREATE INDEX IF NOT EXISTS idx_comments_news   ON comments(news_id);
CREATE INDEX IF NOT EXISTS idx_comments_user   ON comments(user_id);
CREATE INDEX IF NOT EXISTS idx_pwres_user     ON password_resets(user_id);

COMMIT;

-- Notes
-- - users.role limited to: admin | editor | user
-- - news.status limited to: draft | published | archived
-- - comments are deleted automatically when their news is deleted
-- - author/category set to NULL if the referenced row disappears
-- - tags are optional but included to support the UML's List<Tag>

